ask_project/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from ask.views import *
from loginsys.views import *

admin.autodiscover()

urlpatterns = patterns('',

    # =================================================================================================================
    # Pages
    url(r'^$', index),
    url(r'^new/$', index_new),
    url(r'^new_ask/$', new_ask),
    url(r'^ask/([0-9]+)?/$', ask),
    url(r'^profile/([0-9]+)?/$', profile),


    # =================================================================================================================
    # Pagination
    url(r'^page/(\d+)/$', index),
    url(r'^new/page/(\d+)/$', index_new),
    url(r'^ask/([0-9]+)?/page/(\d+)/$', ask),


    # =================================================================================================================
    # Authorization
    url(r'^log_in/$', log_in),
    url(r'^log_out/$', log_out),
    url(r'^register/$', register),
    url(r'^profile/([0-9]+)?/change/$', change_profile),


    # =================================================================================================================
    # Likes
    url(r'^ask/add_like/([0-9]+)?/$', add_ask_like),
    url(r'^ask/rm_like/([0-9]+)?/$', rm_ask_like),

    url(r'^ask/([0-9]+)?/answer/add_like/([0-9]+)?/$', add_answer_like),
    url(r'^ask/([0-9]+)?/answer/rm_like/([0-9]+)?/$', rm_answer_like),


    # =================================================================================================================
    # Add
    url(r'^ask/add_answer/([0-9]+)?/$', add_answer),
    url(r'^new_ask/add_ask/$', add_ask),


    # =================================================================================================================
    # Correct
    url(r'^ask/([0-9]+)?/correct/([0-9]+)?/$', correct_answer),


    # =================================================================================================================
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': '/home/marina/tech@mail.ru/ask_project/static/'}),

    url(r'^uploads/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': '/home/marina/tech@mail.ru/ask_project/uploads/'}),

    url(r'^admin/', include(admin.site.urls)),
)

ask/models.py
# -*- coding:utf-8 -*-
from django.contrib.auth.models import User
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=30, verbose_name='Tag')
    count = models.PositiveIntegerField(default=0)
    class Meta:
        verbose_name_plural = 'Tag'
    def __unicode__(self):
        return self.name

class UserProfile (models.Model):
    user = models.ForeignKey(User, unique=True)
    rating = models.IntegerField(verbose_name='Rating', default=0)
    avatar = models.ImageField(upload_to='avatars', verbose_name='Foto', default='/uploads/default.png')
    def __unicode__(self):
        return self.user.username

class Ask(models.Model):
    title = models.CharField(max_length=100, verbose_name='Title')
    description = models.TextField(verbose_name='Description')
    user = models.ForeignKey(UserProfile)
    create_date = models.DateTimeField(auto_now_add=True)
    rating = models.IntegerField(verbose_name='Rating', default=0)
    tags = models.ManyToManyField(Tag, blank=True)

    class Meta:
        verbose_name = 'questions'
        verbose_name_plural = 'Question'
    def __unicode__(self):
        return self.title

class Answer(models.Model):
    question = models.ForeignKey(Ask)
    description = models.TextField(verbose_name='Answer')
    user = models.ForeignKey(UserProfile)
    create_date = models.DateTimeField(auto_now_add=True)
    rating = models.IntegerField(verbose_name='Rating', default=0)
    correct = models.BooleanField(verbose_name='Correct', default=False)
    class Meta:
        verbose_name = 'answers'
        verbose_name_plural = 'Answer'
    def __unicode__(self):
        return self.description

class LikeAsk(models.Model):
    user = models.ForeignKey(UserProfile)
    ask = models.ForeignKey(Ask)
    is_like = models.BooleanField(verbose_name='Is like?')
    class Meta:
        verbose_name = 'likes_asks'
        verbose_name_plural = 'Like_ask'
    def __unicode__(self):
        return self.user

class LikeAnswer(models.Model):
    user = models.ForeignKey(UserProfile)
    answer = models.ForeignKey(Answer)
    is_like = models.BooleanField(verbose_name='Is like?')
    class Meta:
        verbose_name = 'likes_answers'
        verbose_name_plural = 'Like_answer'
    def __unicode__(self):
        return self.user

loginsys/views.py
from django.shortcuts import render_to_response, redirect
from django.core.context_processors import csrf
from django.contrib.auth.forms import UserCreationForm
from django.contrib import auth
from form import *

def log_in(request):
    args = {}
    args.update(csrf(request))
    args['username'] = auth.get_user(request).username
    if args['username']:
        args['user_id'] = UserProfile.objects.get(user=auth.get_user(request)).id
    args['best_users'] = UserProfile.objects.order_by('-rating')[0:10]
    args['tags'] = Tag.objects.all()
    if request.POST:
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return redirect('/')
        else:
            args['login_error'] = 'User not found.'
            return render_to_response('log_in.html', args)
    return render_to_response('log_in.html', args)

def log_out(request):
    auth.logout(request)
    return redirect("/")

def register(request):
    args = {}
    args.update(csrf(request))
    args['form'] = UserCreationForm()
    args['username'] = auth.get_user(request).username
    if args['username']:
        args['user_id'] = UserProfile.objects.get(user=auth.get_user(request)).id
    args['best_users'] = UserProfile.objects.order_by('-rating')[0:10]
    args['tags'] = Tag.objects.all()
    if request.POST:
        new_user_form = UserCreationForm(request.POST)
        if new_user_form.is_valid():
            new_user_form.save()
            new_user = auth.authenticate(username=new_user_form.cleaned_data['username'],
                                         password=new_user_form.cleaned_data['password2'])
            user = UserProfile(user=new_user)
            user.save()
            auth.login(request, new_user)
            return redirect('/')
        else:
            args['register_error'] = 'Please, enter the correct data.'
            return render_to_response('register.html', args)
    return render_to_response('register.html', args)

def change_profile(request, user_id):
    args = {}
    args.update(csrf(request))
    user_base = auth.get_user(request)
    user_other = UserProfile.objects.get(user=user_base)
    if request.POST:
        form = BaseProfileForm(request.POST)
        other_form = OtherProfileForm(request.POST, request.FILES)
        if form.is_valid() and other_form.is_valid():

            user_base.email = request.POST.get('email', '')
            user_base.first_name = request.POST.get('first_name', '')
            user_base.save()

            user_other.avatar = request.POST.get('avatar', '')
            user_other.save()
            return redirect('/profile/%s/' % user_id, args)
    return redirect('/profile/%s/' % user_id, args)

loginsys/templates/log_in.html
{% extends  'base.html' %}

{% block log_in %}

    <header class="page-header">
    <h1 class="page-title">Log In</h1>
    </header>

	<div class="col-sm-8 col-sm-offset-2">
		<div class="panel panel-default">
			<div class="panel-body">
				<h3 class="thin text-center">Log in to your account</h3>
				<hr>

				<form action="/log_in/" method="post">
                    {% csrf_token %}
                    {% if login_error %}
                        <span class="badge alert-danger">{{ login_error }} Please, try again.</span>
                    {% endif %}
					<div class="top-margin">
						<label>Nickname<span class="text-danger">*</span></label>
						<input name="username" id="username" type="text" class="form-control">
					</div>
					<div class="top-margin">
						<label>Password <span class="text-danger">*</span></label>
						<input name="password" id="password" type="password" class="form-control">
					</div>
					<hr>
					<div class="row">
						<div class="col-lg-12 text-right">
							<button class="btn btn-action" type="submit">Sign in!</button>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>

{% endblock %}
			

loginsys/templates/profile.html
{% extends  'base.html' %}

{% block profile %}

	<header class="page-header">
		<h1 class="page-title">Settings</h1>
	</header>

	<div class="col-sm-10 col-sm-offset-1">
		<div class="panel panel-default">
			<div class="panel-body">
				<h3 class="thin text-center">You can change you settings</h3>
				<hr>

				<form action="/profile/{{ user_other.id }}/change/" enctype="multipart/form-data" method="post">
                {% csrf_token %}
                    <div class="row" align="center">
						<label title="Your rating"><img src="/bootstrap/images/icons/32/778.png"> {{ user_other.rating }}</label>
					</div>
                    <div class="top-margin">
					    <label>Login</label>
					    <input readonly value="{{ user_base.username }}" type="text" class="form-control">
					</div>
					<div class="top-margin">
						<label>E-mail</label>
						<input id="id_email" name="email" value="{{ user_base.email }}" type="text" class="form-control">
					</div>
                    <div class="top-margin">
					    <label>Nickname</label>
					    <input id="id_first_name" name="first_name" value="{{ user_base.first_name }}" type="text" class="form-control" placeholder="Set nickname...">
					</div>
					<div class="top-margin">
						<div class="row">
							<div class="col-lg-4">
                                {% if user_other.avatar %}
								    <img src="/{{ user_other.avatar.url }}" style="padding-bottom:10px">
                                {% else %}
                                    <img src="/bootstrap/images/icons/64/228.png" style="padding-bottom:10px">
                                {% endif %}
							</div>
							<div class="col-lg-8 text-right">
                                   <input id="id_avatar" name="avatar" type="file">
                            </div>
                        </div>
					</div>

					<hr>
					<div class="row">
						<div class="col-lg-12 text-right">
							<button class="btn btn-action" type="submit">Save!</button>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>

{% endblock %}

loginsys/templates/register.html
{% extends  'base.html' %}

{% block register %}

	<header class="page-header">
		<h1 class="page-title">Registration</h1>
	</header>

	<div class="col-sm-10 col-sm-offset-1">
		<div class="panel panel-default">
			<div class="panel-body">
				<h3 class="thin text-center">Register a new account</h3>
				<hr>

				<form action="/register/" method="post">
                    {% csrf_token %}
                    {% if register_error %}
                        <span class="badge alert-danger">{{ register_error }}</span>
                    {% endif %}
					<div class="top-margin">
						<label>Login <span class="text-danger">*</span></label>
						<input id="id_username" maxlength="30" name="username" type="text" class="form-control">
					</div>

					<div class="row top-margin">
						<div class="col-sm-6">
							<label>Password <span class="text-danger">*</span></label>
							<input id="id_password1" name="password1" type="password" class="form-control">
						</div>
						<div class="col-sm-6">
							<label>Confirm Password <span class="text-danger">*</span></label>
							<input id="id_password2" name="password2" type="password" class="form-control">
						</div>
					</div>

					<hr>

					<div class="row">
						<div class="col-lg-12 text-right">
							<button class="btn btn-action" type="submit">Register!</button>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
					
{% endblock %}			