ask_project/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from ask.views import *
from loginsys.views import *

admin.autodiscover()

urlpatterns = patterns('',

    # =================================================================================================================
    # Pages
    url(r'^$', index),
    url(r'^new/$', index_new),
    url(r'^new_ask/$', new_ask),
    url(r'^ask/([0-9]+)?/$', ask),
    url(r'^profile/([0-9]+)?/$', profile),


    # =================================================================================================================
    # Pagination
    url(r'^page/(\d+)/$', index),
    url(r'^new/page/(\d+)/$', index_new),
    url(r'^ask/([0-9]+)?/page/(\d+)/$', ask),


    # =================================================================================================================
    # Authorization
    url(r'^log_in/$', log_in),
    url(r'^log_out/$', log_out),
    url(r'^register/$', register),
    url(r'^profile/([0-9]+)?/change/$', change_profile),


    # =================================================================================================================
    # Likes
    url(r'^ask/add_like/([0-9]+)?/$', add_ask_like),
    url(r'^ask/rm_like/([0-9]+)?/$', rm_ask_like),

    url(r'^ask/([0-9]+)?/answer/add_like/([0-9]+)?/$', add_answer_like),
    url(r'^ask/([0-9]+)?/answer/rm_like/([0-9]+)?/$', rm_answer_like),


    # =================================================================================================================
    # Add
    url(r'^ask/add_answer/([0-9]+)?/$', add_answer),
    url(r'^new_ask/add_ask/$', add_ask),


    # =================================================================================================================
    # Correct
    url(r'^ask/([0-9]+)?/correct/([0-9]+)?/$', correct_answer),


    # =================================================================================================================
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': '/home/marina/tech@mail.ru/ask_project/static/'}),

    url(r'^uploads/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': '/home/marina/tech@mail.ru/ask_project/uploads/'}),

    url(r'^admin/', include(admin.site.urls)),
)

ask/models.py
# -*- coding:utf-8 -*-
from django.contrib.auth.models import User
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=30, verbose_name='Tag')
    count = models.PositiveIntegerField(default=0)
    class Meta:
        verbose_name_plural = 'Tag'
    def __unicode__(self):
        return self.name

class UserProfile (models.Model):
    user = models.ForeignKey(User, unique=True)
    rating = models.IntegerField(verbose_name='Rating', default=0)
    avatar = models.ImageField(upload_to='avatars', verbose_name='Foto', default='/uploads/default.png')
    def __unicode__(self):
        return self.user.username

class Ask(models.Model):
    title = models.CharField(max_length=100, verbose_name='Title')
    description = models.TextField(verbose_name='Description')
    user = models.ForeignKey(UserProfile)
    create_date = models.DateTimeField(auto_now_add=True)
    rating = models.IntegerField(verbose_name='Rating', default=0)
    tags = models.ManyToManyField(Tag, blank=True)

    class Meta:
        verbose_name = 'questions'
        verbose_name_plural = 'Question'
    def __unicode__(self):
        return self.title

class Answer(models.Model):
    question = models.ForeignKey(Ask)
    description = models.TextField(verbose_name='Answer')
    user = models.ForeignKey(UserProfile)
    create_date = models.DateTimeField(auto_now_add=True)
    rating = models.IntegerField(verbose_name='Rating', default=0)
    correct = models.BooleanField(verbose_name='Correct', default=False)
    class Meta:
        verbose_name = 'answers'
        verbose_name_plural = 'Answer'
    def __unicode__(self):
        return self.description

class LikeAsk(models.Model):
    user = models.ForeignKey(UserProfile)
    ask = models.ForeignKey(Ask)
    is_like = models.BooleanField(verbose_name='Is like?')
    class Meta:
        verbose_name = 'likes_asks'
        verbose_name_plural = 'Like_ask'
    def __unicode__(self):
        return self.user

class LikeAnswer(models.Model):
    user = models.ForeignKey(UserProfile)
    answer = models.ForeignKey(Answer)
    is_like = models.BooleanField(verbose_name='Is like?')
    class Meta:
        verbose_name = 'likes_answers'
        verbose_name_plural = 'Like_answer'
    def __unicode__(self):
        return self.user

ask/views.py
from django.shortcuts import render_to_response, redirect
from django.core.exceptions import ObjectDoesNotExist
from django.http.response import Http404
from django.core.context_processors import csrf
from django.core.paginator import Paginator
from form import *


# =====================================================================================================================
def index(request, page_number=1):
    args = {}
    args.update(csrf(request))
    args['questions'] = Paginator(Ask.objects.all().order_by('-rating'), 20).page(page_number)
    args['username'] = auth.get_user(request).username
    args['is_new_sort'] = False
    if args['username']:
        args['user_id'] = UserProfile.objects.get(user=auth.get_user(request)).id
    args['best_users'] = UserProfile.objects.order_by('-rating')[0:10]
    args['tags'] = Tag.objects.all()
    return render_to_response('index.html', args)

def index_new(request, page_number=1):
    args = {}
    args.update(csrf(request))
    args['questions'] = Paginator(Ask.objects.all().order_by('-create_date'), 20).page(page_number)
    args['username'] = auth.get_user(request).username
    args['is_new_sort'] = True
    if args['username']:
        args['user_id'] = UserProfile.objects.get(user=auth.get_user(request)).id
    args['best_users'] = UserProfile.objects.order_by('-rating')[0:10]
    args['tags'] = Tag.objects.all()
    return render_to_response('index.html', args)

def new_ask(request):
    args = {}
    args.update(csrf(request))
    args['form'] = NewAskForm
    args['username'] = auth.get_user(request).username
    if args['username']:
        args['user_id'] = UserProfile.objects.get(user=auth.get_user(request)).id
    args['best_users'] = UserProfile.objects.order_by('-rating')[0:10]
    args['tags'] = Tag.objects.all()
    return render_to_response('new_ask.html', args)

def ask(request, ask_id, page_number=1):
    args = {}
    args.update(csrf(request))
    args['question'] = Ask.objects.get(id=ask_id)
    args['answers'] = Paginator(Answer.objects.filter(question_id=ask_id).order_by('-create_date'), 10).page(page_number)
    args['form'] = AnswerForm
    args['valid_user'] = False
    args['username'] = auth.get_user(request).username
    if args['username']:
        args['user_id'] = UserProfile.objects.get(user=auth.get_user(request)).id
        if Ask.objects.get(id=ask_id).user == UserProfile.objects.get(user=auth.get_user(request)):
            args['valid_user'] = True
    args['best_users'] = UserProfile.objects.order_by('-rating')[0:10]
    args['tags'] = Tag.objects.all()
    return render_to_response('ask.html', args)

def profile(request, user_id):
    args = {}
    args.update(csrf(request))
    args['user_base'] = auth.get_user(request)
    args['user_other'] = UserProfile.objects.get(id=user_id)

    args['username'] = auth.get_user(request).username
    args['user_id'] = UserProfile.objects.get(user=auth.get_user(request)).id
    args['best_users'] = UserProfile.objects.order_by('-rating')[0:10]
    args['tags'] = Tag.objects.all()
    return render_to_response('profile.html', args)


# =====================================================================================================================
def add_ask_like(request, ask_id):
    try:
        like = LikeAsk.objects.get(user=auth.get_user(request), ask=ask_id)
        if like.is_like:
            return redirect('/')
        else:
            quest = Ask.objects.get(id=ask_id)
            user = UserProfile.objects.get(user=quest.user)
            LikeAsk.objects.filter(user=UserProfile.objects.get(user=auth.get_user(request)),
                                   ask=Ask.objects.get(id=ask_id)).delete()
            quest.rating += 1
            user.rating += 1
            user.save()
            quest.save()
            return redirect('/')
    except:
        quest = Ask.objects.get(id=ask_id)
        user = UserProfile.objects.get(user=quest.user)
        LikeAsk(user=UserProfile.objects.get(user=auth.get_user(request)),
                ask=Ask.objects.get(id=ask_id), is_like=True).save()
        quest.rating += 1
        user.rating += 1
        user.save()
        quest.save()
        return redirect('/')


def rm_ask_like(request, ask_id):
    try:
        like = LikeAsk.objects.get(user=auth.get_user(request), ask=ask_id)
        if not like.is_like:
            return redirect('/')
        else:
            quest = Ask.objects.get(id=ask_id)
            user = UserProfile.objects.get(user=quest.user)
            LikeAsk.objects.get(user=UserProfile.objects.get(user=auth.get_user(request)),
                                ask=Ask.objects.get(id=ask_id)).delete()
            quest.rating -= 1
            user.rating -= 1
            user.save()
            quest.save()
            return redirect('/')
    except:
        quest = Ask.objects.get(id=ask_id)
        user = UserProfile.objects.get(user=quest.user)
        LikeAsk(user=UserProfile.objects.get(user=auth.get_user(request)),
                ask=Ask.objects.get(id=ask_id), is_like=False).save()
        quest.rating -= 1
        user.rating -= 1
        user.save()
        quest.save()
        return redirect('/')


# =====================================================================================================================
def add_answer_like(request, ask_id, answer_id):
    try:
        like = LikeAnswer.objects.get(user=auth.get_user(request), answer=answer_id)
        if like.is_like:
            return redirect('/ask/%s/' % ask_id)
        else:
            answer = Answer.objects.get(id=answer_id)
            user = UserProfile.objects.get(user=answer.user)
            LikeAnswer.objects.filter(user=UserProfile.objects.get(user=auth.get_user(request)),
                                      answer=Answer.objects.get(id=answer_id)).delete()
            answer.rating += 1
            user.rating += 1
            user.save()
            answer.save()
            return redirect('/ask/%s/' % ask_id)
    except:
        answer = Answer.objects.get(id=answer_id)
        user = UserProfile.objects.get(user=answer.user)
        LikeAnswer(user=UserProfile.objects.get(user=auth.get_user(request)),
                   answer=Answer.objects.get(id=answer_id), is_like=True).save()
        answer.rating += 1
        user.rating += 1
        user.save()
        answer.save()
        return redirect('/ask/%s/' % ask_id)


def rm_answer_like(request, ask_id, answer_id):
    try:
        like = LikeAnswer.objects.get(user=auth.get_user(request), answer=answer_id)
        if not like.is_like:
            return redirect('/ask/%s/' % ask_id)
        else:
            answer = Answer.objects.get(id=answer_id)
            user = UserProfile.objects.get(user=answer.user)
            LikeAnswer.objects.get(user=UserProfile.objects.get(user=auth.get_user(request)),
                                   answer=Answer.objects.get(id=answer_id)).delete()
            answer.rating -= 1
            user.rating -= 1
            user.save()
            answer.save()
            return redirect('/ask/%s/' % ask_id)
    except:
        answer = Answer.objects.get(id=answer_id)
        user = UserProfile.objects.get(user=answer.user)
        LikeAnswer(user=UserProfile.objects.get(user=auth.get_user(request)),
                   answer=Answer.objects.get(id=answer_id), is_like=False).save()
        answer.rating -= 1
        user.rating -= 1
        user.save()
        answer.save()
        return redirect('/ask/%s/' % ask_id)


# =====================================================================================================================
def add_answer(request, ask_id):
    if request.POST:
        form = AnswerForm(request.POST)
        if form.is_valid():
            answ = form.save(commit=False)
            answ.question = Ask.objects.get(id=ask_id)
            answ.user = UserProfile.objects.get(user=auth.get_user(request))
            form.save()
            description = request.POST.get('description', '')
            ask_user = User.objects.get(id=UserProfile.objects.get(ask=ask_id).id)
        return redirect('/ask/%s/' % ask_id)

def add_ask(request):
    args = {}
    args.update(csrf(request))
    if request.POST:
        form = NewAskForm(request.POST)
        if form.is_valid():
            new_ask = form.save(commit=False)
            new_ask.user = UserProfile.objects.get(user=auth.get_user(request))
            tags_array = request.POST.get('name', '')
            form.save()
            for tag in tags_array.split(', '):
                if tag != '':
                    try:
                        tag = Tag.objects.get(name=tag)
                        tag.count += 1
                        tag.save()
                        new_ask.tags.add(tag)
                    except:
                        t = Tag.objects.create(name=tag, count=1)
                        t.save()
                        new_ask.tags.add(Tag.objects.get(name=tag))
            return redirect('/new/')
        else:
            args['add_ask_error'] = 'Please, enter the correct data.'
            return render_to_response('new_ask.html', args)


# =====================================================================================================================
def correct_answer(request, ask_id, answer_id):
    try:
        answer = Answer.objects.get(id=answer_id)
        if answer.correct:
            answer.correct = False
        else:
            answer.correct = True
        answer.save()
    except ObjectDoesNotExist:
        raise Http404
    return redirect('/ask/%s/' % ask_id)

templates/ask.html
{% extends  'base.html' %}

{% block ask %}

	<!-- Question -->
	<div class="row">
        <div class="col-sm-2">
            <div align="center"><img src="/bootstrap/images/icons/64/902.png"></div>
            <a href="/ask/add_like/{{question.id}}/"><div align="center"><img src="/bootstrap/images/icons/32/994.png"></div></a>
            <div align="center"><b>{{question.rating}}</b></div>
            <a href="/ask/rm_like/{{question.id}}/"><div align="center"><img src="/bootstrap/images/icons/32/995.png"></div></a>
        </div>

        <div class="col-sm-10">
            <div>
                <h3 style="margin-top:10px">{{question.title}}</h3>
            </div>
            <p style="padding:5px">{{question.description}}</p>

            <footer>
                <div class="meta">
                    <h6><b><ins>{{ question.user }}</ins></b>
                    <img src="/bootstrap/images/icons/16/243.png" style="padding-left:10px">
                    {{ question.create_date }}
                   <img src="/bootstrap/images/icons/16/535.png" style="padding-left:10px">Tags:
                        <a href="">tag</a>
                        <a href="">tag</a>
                        <a href="">tag</a>
                    </h6>
                </div>
            </footer>
        </div>
	</div>

	<!-- Answer -->
	{% for answer in answers %}
	<div class="row">
        <div class="col-sm-12">
            <hr>
            <p>{{answer.description}}</p>
            <div class="row">
                <div class="col-sm-7">
                    <footer>
                        <div class="meta">
                            <h6>
                                <img src="/bootstrap/images/icons/64/902.png">
                                <b><ins>{{ answer.user }}</ins></b>
                                <img src="/bootstrap/images/icons/16/243.png" style="padding-left:10px">
                                {{ answer.create_date }}
                            </h6>
                        </div>
                    </footer>
                </div>
                <div class="col-sm-2" style="padding-top:25px">
                    {% if valid_user %}
                        {% if answer.correct %}
                            <a href="/ask/{{ question.id }}/correct/{{ answer.id }}">
                                <span class="badge alert-success">Correct!</span>
                            </a>
                        {% else %}
                            <a href="/ask/{{ question.id }}/correct/{{ answer.id }}">
                                <span style="border:1px dashed; padding:2px">Correct</span>
                            </a>
                        {% endif %}
                    {% else %}
                        {% if answer.correct %}
                            <span class="badge alert-success">Correct!</span>
                        {% endif %}
                    {% endif %}
                </div>
                <div class="col-sm-3" style="padding-top:20px">
                    {% if username %}
                        <a href="/ask/{{ question.id}}/answer/rm_like/{{ answer.id }}/"><img src="/bootstrap/images/icons/32/992.png"></a>
                    {% else %}
                        <img src="/bootstrap/images/icons/32/992-1.png">
                    {% endif %}
                        <b>{{answer.rating}}</b>
                    {% if username %}
                        <a href="/ask/{{ question.id }}/answer/add_like/{{ answer.id }}/"><img src="/bootstrap/images/icons/32/993.png"></a>
                    {% else %}
                        <img src="/bootstrap/images/icons/32/993-1.png">
                    {% endif %}
                </div>
            </div>
        </div>

        <!--<div class="col-sm-2">-->
            <!--<div align="center"><img src="/bootstrap/images/icons/64/902.png"></div>-->
            <!--<a href=""><div align="center"><img src="/bootstrap/images/icons/32/994.png"></div></a>-->
            <!--<div align="center"><b>{{answer.rating}}</b></div>-->
            <!--<a href=""><div align="center"><img src="/bootstrap/images/icons/32/995.png"></div></a>-->
        <!--</div>-->
	</div>
	{% endfor %}

    {% if username %}
	<hr>
    <form action="/ask/add_answer/{{question.id}}/" method="post">
    {% csrf_token %}
	<div class="row">
		<div class="col-sm-12">
            <textarea id="id_description" name="description" placeholder="Enter your answer..." class="form-control" rows="5"></textarea>
			<hr>
		    <div class="row">
				<div class="col-sm-12 text-right">
					<input type="submit" class="btn btn-action" value="ASK!">
				</div>
			</div>
		</div>
	</div>
    </form>
    {% endif %}


    <div class="row text-center">
        <div class="col-lg-12">
            <ul class="pagination">

                {% if answers.has_previous %}
                    <li class="arrow"><a href="/ask/{{ question.id }}/page/1">start</a></li>
                    <li class="arrow"><a href="/ask/{{ question.id }}/page/{{ answers.previous_page_number }}">←</a></li>
                {% else %}
                    <li><a>start</a></li>
                    <li><a>←</a></li>
                {% endif %}

                {% for page in answers.paginator.page_range %}
                    {% if page == answers.number %}

                        {% if answers.has_previous %}
                            <li><a href="/ask/{{ question.id }}/page/{{ answers.previous_page_number }}">{{ answers.previous_page_number }}</a></li>
                        {% endif %}

                        <li class="current"><a href=""><b>{{ page }}</b></a></li>

                        {% if answers.has_next %}
                            <li><a href="/ask/{{ question.id }}/page/{{ answers.next_page_number }}">{{ answers.next_page_number }}</a></li>
                        {% endif %}

                    {% endif %}
                {% endfor %}

                {% if answers.has_next %}
                    <li class="arrow"><a href="/ask/{{ question.id }}/page/{{ answers.next_page_number }}">→</a></li>
                    <li class="arrow"><a href="/ask/{{ question.id }}/page/{{ answers.paginator.num_pages }}">end</a></li>
                {% else %}
                    <li><a>→</a></li>
                    <li><a>end</a></li>
                {% endif %}
            </ul>
        </div>
	</div>


    <!--<div class="row text-center">-->

    <!--<div class="col-lg-12">-->
        <!--<ul class="pagination">-->
		    <!--<li><a href="#">«</a></li>-->
		    <!--<li><a href="#">1</a></li>-->
		    <!--<li><a href="#">2</a></li>-->
		    <!--<li><a href="#">3</a></li>-->
		    <!--<li><a href="#">4</a></li>-->
		    <!--<li><a href="#">»</a></li>-->
        <!--</ul>-->
    <!--</div>-->

	<!--</div>-->

{% endblock %}

templates/index.html
{% extends  'base.html' %}

{% block index %}

	<div class="tabbable">
 		<ul class="nav nav-tabs">
 			{% if is_new_sort %}
            <li><a href="/">Hot Questions</a></li>
            <li class="active"><a href="/new/">New Questions</a></li>
            {% else %}
            <li class="active"><a href="/">Hot Questions</a></li>
            <li><a href="/new/">New Questions</a></li>
            {% endif %}
  		</ul>
	</div>

    {% for question in questions %}
    <div class="row" style="padding-top:10px">
        <div class="col-md-2">
            <div align="center"><img src="/bootstrap/images/icons/64/902.png"></div>
            {% if username %}
                <a href="/ask/add_like/{{question.id}}/"><div align="center"><img src="/bootstrap/images/icons/32/994.png"></div></a>
            {% else %}
                <div align="center"><img src="/bootstrap/images/icons/32/994-1.png"></div>
            {% endif %}
            <div align="center"><b>{{ question.rating }}</b></div>
            {% if username %}
                <a href="/ask/rm_like/{{question.id}}/"><div align="center"><img src="/bootstrap/images/icons/32/995.png"></div></a>
            {% else %}
                <div align="center"><img src="/bootstrap/images/icons/32/995-1.png"></div>
            {% endif %}
        </div>

        <div class="col-md-10">
            <div>
                <a href="/ask/{{question.id}}/"><h3 style="margin-top:10px">{{ question.title }}</h3></a>
            </div>
            <p style="padding:5px">{{ question.description }}</p>

            <footer>
                <div class="meta">
                    <h6>
                    <a href="/ask/{{question.id}}/" ><b>Answers({{ question.answer_set.count }}) </b></a>
                    <img src="/bootstrap/images/icons/16/723.png" style="padding-left:10px">
                    <b><ins>{{ question.user }}</ins></b>
                    <img src="/bootstrap/images/icons/16/243.png" style="padding-left:10px">
                    {{ question.create_date }}
                    {% if question.tags.all %}
                        <img src="/bootstrap/images/icons/16/535.png" style="padding-left:10px">Tags:
                        {% for tag in question.tags.all %}
                            <a href=""><ins>{{ tag }}</ins></a>
                        {% endfor %}
                    {% endif %}
                    </h6>
                </div>
            </footer>
        </div>
    </div>
    {% endfor %}

    <div class="row text-center">
        <div class="col-lg-12">
            <ul class="pagination">

                {% if questions.has_previous %}
                    <li class="arrow"><a href="/page/1">start</a></li>
                    <li class="arrow"><a href="/page/{{ questions.previous_page_number }}">←</a></li>
                {% else %}
                    <li><a>start</a></li>
                    <li><a>←</a></li>
                {% endif %}

                {% for page in questions.paginator.page_range %}
                    {% if page == questions.number %}

                        {% if questions.has_previous %}
                            <li><a href="/page/{{ questions.previous_page_number }}">{{ questions.previous_page_number }}</a></li>
                        {% endif %}

                        <li class="current"><a href=""><b>{{ page }}</b></a></li>

                        {% if questions.has_next %}
                            <li><a href="/page/{{ questions.next_page_number }}">{{ questions.next_page_number }}</a></li>
                        {% endif %}

                    {% endif %}
                {% endfor %}

                {% if questions.has_next %}
                    <li class="arrow"><a href="/page/{{ questions.next_page_number }}">→</a></li>
                    <li class="arrow"><a href="/page/{{ questions.paginator.num_pages }}">end</a></li>
                {% else %}
                    <li><a>→</a></li>
                    <li><a>end</a></li>
                {% endif %}
            </ul>
        </div>
	</div>

{% endblock %}

templates/new.html
{% extends  'base.html' %}

{% block index %}

	<div class="tabbable">
 		<ul class="nav nav-tabs">
            <li><a href="/">Hot Questions</a></li>
            <li class="active"><a href="/new/">New Questions</a></li>
  		</ul>
	</div>

    {% for question in questions %}
    <div class="row" style="padding-top:10px">
        <div class="col-md-2">
            <div align="center"><img src="/bootstrap/images/icons/64/902.png"></div>
            {% if username %}
                <a href="/ask/add_like/{{question.id}}/"><div align="center"><img src="/bootstrap/images/icons/32/994.png"></div></a>
            {% else %}
                <div align="center"><img src="/bootstrap/images/icons/32/994-1.png"></div>
            {% endif %}
            <div align="center"><b>{{question.rating}}</b></div>
            {% if username %}
                <a href="/ask/rm_like/{{question.id}}/"><div align="center"><img src="/bootstrap/images/icons/32/995.png"></div></a>
            {% else %}
                <div align="center"><img src="/bootstrap/images/icons/32/995-1.png"></div>
            {% endif %}
        </div>

        <div class="col-md-10">
            <div>
                <a href="/ask/{{question.id}}/"><h3 style="margin-top:10px">{{question.title}}</h3></a>
            </div>
            <p style="padding:5px">{{question.description}}</p>

            <footer>
                <div class="meta">
                    <h6><b><ins>{{ question.user }}</ins></b>
                    <img src="/bootstrap/images/icons/16/243.png" style="padding-left:10px">
                    {{ question.create_date }}
                   <img src="/bootstrap/images/icons/16/535.png" style="padding-left:10px">Tags:
                        <a href="">tag</a>
                        <a href="">tag</a>
                        <a href="">tag</a>
                    </h6>
                </div>
            </footer>
        </div>
    </div>
    {% endfor %}

    <div class="row text-center">
        <div class="col-lg-12">
            <ul class="pagination">

                {% if quest.has_previous %}
                    <li class="arrow"><a href="/page/1">start</a></li>
                    <li class="arrow"><a href="/page/{{ quest.previous_page_number }}">←</a></li>
                {% else %}
                    <li><a>start</a></li>
                    <li><a>←</a></li>
                {% endif %}

                {% for page in quest.paginator.page_range %}
                    {% if page == quest.number %}

                        {% if quest.has_previous %}
                            <li><a href="/page/{{ quest.previous_page_number }}">{{ quest.previous_page_number }}</a></li>
                        {% endif %}

                        <li class="current"><a href=""><b>{{ page }}</b></a></li>

                        {% if quest.has_next %}
                            <li><a href="/page/{{ quest.next_page_number }}">{{ quest.next_page_number }}</a></li>
                        {% endif %}

                    {% endif %}
                {% endfor %}

                {% if quest.has_next %}
                    <li class="arrow"><a href="/page/{{ quest.next_page_number }}">→</a></li>
                    <li class="arrow"><a href="/page/{{ quest.paginator.num_pages }}">end</a></li>
                {% else %}
                    <li><a>→</a></li>
                    <li><a>end</a></li>
                {% endif %}
            </ul>
        </div>
	</div>

{% endblock %}

templates/new_ask.html
{% extends  'base.html' %}

{% block ask %}
			
	<header class="page-header">
		<h1 class="page-title">New Question</h1>
	</header>

	<form action="/new_ask/add_ask/" method="post">
    {% csrf_token %}

        {% if add_ask_error %}
            <span class="badge alert-danger">{{ add_ask_error }}</span>
        {% endif %}

		<div class="row top-margin">
			<div class="col-sm-2">
				<h4>Title</h4>
			</div>
			<div class="col-sm-10">
				<input id="id_title" name="title" class="form-control" type="text" placeholder="Type your question here...">
			</div>
		</div>

		<div class="row top-margin">
			<div class="col-sm-12">
				<textarea id="id_description" name="description" placeholder="Describe your question here..." class="form-control" rows="9"></textarea>
			</div>
		</div>

		<br>
		<div class="row">
			<div class="col-sm-2">
				<h4>Tags</h4>
			</div>
            <div class="col-sm-10">
            	<input id="id_name" name="name" class="form-control" type="text" placeholder="tags">
            </div>
		</div>

		<hr>
		<div class="row">
			<div class="col-sm-12 text-right">
				<input class="btn btn-action" type="submit" value="Ask!">
			</div>
		</div>
	</form>
	
	<section class="container-full top-space">
		<div id="map"></div>
	</section>
	
{% endblock %}